import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — BLACK BUILDER" },
      {
        name: "description",
        content:
          "BLACK BUILDER privacy policy: what data we collect, how we use it, and your rights.",
      },
      { property: "og:title", content: "Privacy Policy — BLACK BUILDER" },
      {
        property: "og:description",
        content: "What data BLACK BUILDER collects and how it is used.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <main className="min-h-dvh bg-background px-4 py-12 text-foreground">
      <div className="mx-auto max-w-2xl">
        <Link
          to="/"
          className="mb-8 inline-block font-mono text-xs uppercase tracking-widest text-muted-foreground hover:text-primary"
        >
          ← Back to BLACK BUILDER
        </Link>

        <h1 className="font-sans text-3xl font-bold tracking-tight text-primary">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">Effective: September 23, 2026</p>

        <section className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/90">
          <p>
            This Privacy Policy explains how BLACK BUILDER (“we”, “us”, or “our”) collects, uses,
            stores, and shares your personal information when you use our website and services.
          </p>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              1. Information we collect
            </h2>
            <ul className="list-disc space-y-1 pl-5 text-muted-foreground">
              <li>
                <strong className="text-foreground">Account data:</strong> email address, password
                hash, and any profile information you provide.
              </li>
              <li>
                <strong className="text-foreground">Prompts and outputs:</strong> the text,
                files, and other inputs you submit, plus the apps, code, previews, and artifacts
                generated by the agent swarm.
              </li>
              <li>
                <strong className="text-foreground">Usage data:</strong> browser type, device
                information, IP address, and actions taken in the workspace.
              </li>
              <li>
                <strong className="text-foreground">Third-party auth data:</strong> when you sign
                in with Google, we receive the name, email, and profile data you choose to share.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              2. How we use your information
            </h2>
            <ul className="list-disc space-y-1 pl-5 text-muted-foreground">
              <li>To provide, operate, and improve BLACK BUILDER.</li>
              <li>To authenticate you and keep your account secure.</li>
              <li>To run the agent swarm on your prompts and generate the outputs you request.</li>
              <li>To respond to support requests and send service-related notices.</li>
            </ul>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              3. Data storage and security
            </h2>
            <p>
              Your data is stored in secure cloud databases and object storage. We use encryption
              in transit and at rest, access controls, and row-level security to protect your
              information. No system is completely secure, and we cannot guarantee absolute
              protection.
            </p>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              4. Third-party services
            </h2>
            <p>
              We use trusted providers for authentication, hosting, database, and AI inference. These
              providers may process your data only as necessary to perform the services we contract
              them for and are bound by confidentiality obligations.
            </p>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              5. Your rights
            </h2>
            <p>
              Depending on where you live, you may have the right to access, correct, delete, or
              export your personal data. You can update your account information in your workspace
              settings or contact us to request deletion.
            </p>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">
              6. Changes to this policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will post the revised version
              here with a new effective date.
            </p>
          </div>

          <div>
            <h2 className="mb-2 font-sans text-lg font-semibold text-foreground">7. Contact</h2>
            <p>
              Questions about this Privacy Policy? Reach out via the support channel in your
              workspace.
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}
